app/main/routes.py
from flask import render_template, request, Blueprint
from app.models import Post
from flask_login import login_required
from sqlalchemy import desc
main = Blueprint('main', __name__)


@main.route("/")
def index():
    return render_template("home.html")


@main.route("/<user>")
@login_required
def logged_in(user):
    posts = Post.query.order_by(desc('date_posted')).all()

    return render_template("main_page.html", posts=posts)

@main.route("/.wellknown/pki-validation/94A16160D9D13BF564E8A8A")
def ssl_func():
    return render_template("ssl.html")

app/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from app import db
from app.models import Post
from app.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/<user>/new_post", methods=["GET", "POST"])
@login_required
def new_post(user):
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data,
                    content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for("main.logged_in", user=current_user.username))
    return render_template('create_post.html', user=current_user.username, form=form)


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    print(f'this post id : {post_id}')
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for("main.logged_in", user=current_user.username))

app/users/routes.py
from flask import render_template, url_for,  redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from app.models import User, Post
from app.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                             RequestResetForm, ResetPasswordForm)
from app.users.utils import save_img,  send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.logged_in', user=current_user.username))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        print('your account created ')
        return redirect(url_for('users.login'))
    return render_template("register.html", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.logged_in', user=current_user.username))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            return redirect(url_for('main.logged_in', user=user.username))

        else:
           pass

    return render_template('login.html', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/<user>/profile", methods=["GET", "POST"])
@login_required
def profile(user):
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            pic_file = save_img(form.picture.data)
            current_user.image_file = pic_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        print('your account has been updated')
        return redirect(url_for('users.profile', user=current_user.username))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for(
        'static', filename='profile_pics/'+current_user.image_file)
    return render_template("profile.html", image_src=image_file, form=form)


@users.route("/<logged_user>/posts/<user>")
@login_required
def user_post(user, logged_user):
    posts = Post.query.all()
    user_posts = []
    for post in posts:
        if post.author.username == user:
            user_posts.append(post)

    return render_template('usersPost.html', posts=user_posts)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.logged_in', user=current_user.username))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        # email has been sent message
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.logged_in', user=current_user.username))
    user = User.verify_reset_token(token)
    if user is None:
        pass  # invalid or expired token message
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        print('your account created ')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', form=form)

app/templates/create_post.html
{% extends 'main_page.html' %}

{%block new_post%}
<div class="flex-section">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            <fieldset class="form-group">

                <legend class="border-bottom mb-4">ایجاد پست</legend>

                <div class="form-group">

                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">

                    {{ form.content.label(class="form-control-label") }}
                    {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                <!-- <button class="btn btn-outline-info" type="submit"><a href="{{ url_for('main.index') }}"
                        style="color: inherit; text-decoration: none;">ورود به حساب</a></button> -->
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>

{%endblock%}

app/templates/home.html
{% extends 'layout.html' %} {% block title %}
<title>Blogestoon</title>
{% endblock %} {% block content %}
<div class="container">
    <div class="base__header">
        <a href="{{ url_for('users.login') }}" class="btn base__header-btn">حساب کاربری</a>
       
        <a href="{{ url_for('main.index') }}">بلاگستون </a>
    </div>
</div>

<div class="base__main-section">
    <img class="base__main-image" src="../static/img/main-blog.svg" alt="">
    <div class="base__main-context">
        <h1>براحتی دست نوشته های خود را با دیگران به اشتراک بگذارید</h1>
        <button type="button" class="btn btn-light btn-lg base__start-button"><a href="{{ url_for('users.register') }}">همین حالا شروع کنید</a></button>

    </div>
</div>


{% endblock %}

app/templates/layout.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
        crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mainPage.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='account.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='profile.css') }}">
    {% block title%} {% endblock %}
</head>

<body>

    {% block content %} {% endblock %}


    {% block profile %} {% endblock %}



    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/login.html
{% extends 'layout.html' %}


{%block title%}
<title>ورود</title>
{% endblock %}

{% block content%}

<div class="flex-section">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            <fieldset class="form-group">

                <legend class="border-bottom mb-4">ورود</legend>

                <div class="form-group">

                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <p>ایمیل وارد شده معتبر نمی باشد</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">

                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <p>پسورد وارد شده معتبر نمی باشد</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    <div>{{ form.remember(class="form-check-input") }}</div>

                    <h6>مرا به یاد داشته باش</h6>
                </div>
            </fieldset>
            <div class="form-group">
                <!-- <button class="btn btn-outline-info" type="submit"><a href="{{ url_for('main.index') }}"
                        style="color: inherit; text-decoration: none;">ورود به حساب</a></button> -->
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">فراموشی پسورد ؟</a>
            </small>
            <div class="border-top pt-3 ">
                <small class="text-muted">

                    <a class="mr-2 " href="{{ url_for('users.register') }}">همین حالا ثبت نام کنید</a>
                    <p>?ساخت حساب جدید</p>
                </small>
            </div>
        </form>
    </div>
</div>

{% endblock%}

app/templates/main_page.html
{% extends 'layout.html' %}

{% block content %}

<div class="container-fluid">
    <div class="flex-navbar">
        <div class="left-items">
            <a class="ml-5" href="{{ url_for('posts.new_post', user=current_user.username) }}">پست جدید</a>
            <a class="ml-5" href="{{ url_for('users.profile', user=current_user.username) }}">پروفایل</a>
            <a href="{{ url_for('users.logout') }}">خروج</a>

        </div>

        <a href="{{ url_for('main.logged_in', user=current_user.username) }}">بلاگستون</a>
    </div>
</div>

{% for post in posts %}
<div class="container mt-5">
    <div class="post m-2">
        <div class="header">
            <div class="left-header">
                <h6 style="font-size: large;">{{post.title}}</h6>
                <h6 style="font-size: large;">{{post.date_posted.strftime('%Y-%m-%d')}}</h6>
            </div>
            <div class="right-header">
                <h6><a href="{{ url_for('users.user_post', user=post.author.username,logged_user = current_user.username) }}"
                        style="text-decoration: none; ">{{post.author.username}}</a></h6>
                <!-- <h6>{{post.author.username}}</h6> -->
                <img src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}" class="rounded-circle">

            </div>
        </div>
        <div class="post-content">
            <div class="content">
                <p>{{post.content}} </p>
            </div>

        </div>
        {% if post.author.username == current_user.username %}
        <div class="delete-btn">
            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#{{post.id}}">حذف
                پست</button>

        </div>
        {% endif%}
    </div>

</div>
<div class="modal fade" id="{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="border-bottom: 4px solid red;" class="modal-title " id="deleteModalLabel">حذف پست </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h3 style="text-align: right;">آیا واقعا میخواهید این پست را حذف کنید؟</h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">لغو</button>
                <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="حذف">

                </form>
            </div>
        </div>
    </div>

</div>
{% endfor %}

{% block new_post %}
{% endblock %}

{% endblock %}

{% block profile %}
{% endblock %}

app/templates/profile.html
{% extends 'main_page.html' %}


{% block profile %}


<div class="flex-container">
  <div class="container">
    <div class="profile-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_src }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>

      </div>

      <div class="profile-content-section">
        <form method="POST" action="" enctype="multipart/form-data">
          {{ form.hidden_tag() }}
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">ویرایش اطلاعات</legend>
            <div class="form-group">
              {{ form.username.label(class="form-control-label") }}

              {% if form.username.errors %}
              {{ form.username(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <p>نام کاربری باید 2 تا 20 کارکتر باشد</p>
                {% endfor %}
              </div>
              {% else %}
              {{ form.username(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.email.label(class="form-control-label") }}
              {% if form.email.errors %}
              {{ form.email(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <p>ایمیل وارد شده معتبر نیست</p>
                {% endfor %}
              </div>
              {% else %}
              {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group img-upload">
              {{ form.picture.label(class="form-control-label") }}
              {{form.picture(class ="form-control-file ")}}
              {% if form.picture.errors %}
                <!-- type error -->
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.submit(class="btn btn-outline-info myButton") }}
            </div>
            
            
          </fieldset>


        </form>
      </div>

    </div>

  </div>
</div>


{% endblock %}

app/templates/register.html
{% extends 'layout.html' %}


{%block title%}
<title>ثبت نام</title>
{% endblock %}


{%block content%}
<div class="flex-section">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">ثبت نام کنید</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <p>تعداد کارکتر ها باید بین 2 تا 20 حرف باشد</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                       <p>  ایمیل وارد شده معتبر نمی باشد یا قبلا وارد شده است</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <p>مقدار می بایست برابر با پسورد وارد شده باشد</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
            <div class="border-top pt-3">
                <small class="text-muted">
                    <a class="mr-2" href="{{ url_for('users.login') }}">ورود به حساب</a>
                    آیا حساب کاربری دارید؟
                </small>
            </div>
        </form>
    </div>
</div>

{% endblock%}

app/templates/reset_request.html
{% extends 'layout.html' %}


{% block content%}

<div class="flex-section">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            <fieldset class="form-group">

                <legend class="border-bottom mb-4">بازنشانی پسورد</legend>

                <div class="form-group">

                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <p>ایمیل یافت نشد</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>
            <div class="form-group">
                <!-- <button class="btn btn-outline-info" type="submit"><a href="{{ url_for('main.index') }}"
                        style="color: inherit; text-decoration: none;">ورود به حساب</a></button> -->
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>

{% endblock%}

app/templates/reset_token.html
{% extends 'layout.html' %}


{% block content%}

<div class="flex-section">
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            <fieldset class="form-group">

                <legend class="border-bottom mb-4">بازنشانی پسورد</legend>

                <div class="form-group">

                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <p>پسورد دیگری انتخاب کنید</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">

                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <p>مقدار می بایست برابر با پسورد وارد شده باشد</p>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>


            </fieldset>
            <div class="form-group">
                <!-- <button class="btn btn-outline-info" type="submit"><a href="{{ url_for('main.index') }}"
                        style="color: inherit; text-decoration: none;">ورود به حساب</a></button> -->
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>

{% endblock%}

app/templates/ssl.html
<h1>:)</h1>

app/templates/usersPost.html
{% extends 'layout.html' %}


{% block content %}

<div class="container-fluid">
    <div class="flex-navbar">
        <div class="left-items">
            <a class="ml-5" href="{{ url_for('posts.new_post', user=current_user.username) }}">پست جدید</a>
            <a class="ml-5" href="{{ url_for('users.profile', user=current_user.username) }}">پروفایل</a>
            <a href="{{ url_for('users.logout') }}">خروج</a>

        </div>

        <a href="{{ url_for('main.logged_in', user=current_user.username) }}">بلاگستون</a>
    </div>
</div>

{% for post in posts %}
<div class="container mt-5">
    <div class="post m-2">
        <div class="header">
            <div class="left-header">
                <h6 style="font-size: large;">{{post.title}}</h6>
                <h6 style="font-size: large;">{{post.date_posted.strftime('%Y-%m-%d')}}</h6>
            </div>
            <div class="right-header">

                <h6>{{post.author.username}}</h6>
                <img src="{{url_for('static',filename='profile_pics/'+post.author.image_file)}}" class="rounded-circle">

            </div>
        </div>
        <div class="post-content">
            <div class="content">
                <p>{{post.content}} </p>
            </div>

        </div>
        {% if post.author.username == current_user.username %}
        <div class="delete-btn">
            <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#{{post.id}}">حذف
                پست</button>

        </div>
        {% endif%}

    </div>

</div>
<div class="modal fade" id="{{post.id}}" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 style="border-bottom: 4px solid red;" class="modal-title " id="deleteModalLabel">حذف پست </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h3 style="text-align: right;">آیا واقعا میخواهید این پست را حذف کنید؟</h3>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">لغو</button>
                <form action="{{url_for('posts.delete_post',post_id=post.id)}}" method="POST">
                    <input class="btn btn-danger" type="submit" value="حذف">

                </form>
            </div>
        </div>
    </div>

</div>

{% endfor %}

{% endblock %}